# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/puzzle_output.proto
# Protobuf Python Version: 5.29.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc1',
    'proto/puzzle_output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/puzzle_output.proto\"\xcd\x01\n\x0cPuzzleOutput\x12)\n\tsolutions\x18\x01 \x03(\x0b\x32\x16.PuzzleOutput.Solution\x1a\x91\x01\n\x08Solution\x12\x11\n\tpuzzle_id\x18\x01 \x01(\x05\x12\x0e\n\x06solved\x18\x02 \x01(\x08\x12-\n\x04path\x18\x03 \x03(\x0b\x32\x1f.PuzzleOutput.Solution.PathStep\x1a\x33\n\x08PathStep\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x11\n\tdirection\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.puzzle_output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUZZLEOUTPUT']._serialized_start=30
  _globals['_PUZZLEOUTPUT']._serialized_end=235
  _globals['_PUZZLEOUTPUT_SOLUTION']._serialized_start=90
  _globals['_PUZZLEOUTPUT_SOLUTION']._serialized_end=235
  _globals['_PUZZLEOUTPUT_SOLUTION_PATHSTEP']._serialized_start=184
  _globals['_PUZZLEOUTPUT_SOLUTION_PATHSTEP']._serialized_end=235
# @@protoc_insertion_point(module_scope)
